title: MateUBA PDE
author:
  name: Martín Maas
  email: martin.d.maas@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Basic PDE solvers via Finite Differences and Finite Elements,
  meant for educational purposes. Develped as a part of a course in 
  Numerical Analysis of PDEs, University of Buenos Aires. 

show_excerpts: false # set to true to show excerpts on the homepage

markdown: kramdown
kramdown:
   math_engine: mathjax

# Build settings
theme: jekyll-theme-slate

plugins:
 - jekyll-feed
 - jekyll-seo-tag
